// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_wallet_card/test/flutter_wallet_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:flutter_wallet_card/core/wallet_platform.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WalletPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletPlatform extends _i1.Mock implements _i2.WalletPlatform {
  MockWalletPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WalletPlatformType get platformType => (super.noSuchMethod(
        Invocation.getter(#platformType),
        returnValue: _i2.WalletPlatformType.ios,
      ) as _i2.WalletPlatformType);

  @override
  _i3.Future<bool> isWalletAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isWalletAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isCardAdded(String? identifier) => (super.noSuchMethod(
        Invocation.method(
          #isCardAdded,
          [identifier],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> addToWallet(
    _i4.File? file, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToWallet,
          [file],
          {#metadata: metadata},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> viewInWallet(String? identifier) => (super.noSuchMethod(
        Invocation.method(
          #viewInWallet,
          [identifier],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
