# GitHub Pages configuration
title: Flutter Wallet Card
description: A unified Flutter plugin for adding cards to Apple Wallet and Google Wallet
url: "https://webeferen.github.io"
baseurl: "/flutter_wallet_card"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - getting-started.md
  - api-reference.md
  - platform-setup.md
  - examples.md
  - migration.md

# Social links
github_username: webeferen

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Code highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false