name: Publish to pub.dev

# Modern OIDC-based publishing workflow using dart-lang/setup-dart reusable workflow
# 
# Setup Requirements:
# 1. Enable automated publishing on pub.dev in package Admin tab
# 2. Configure GitHub repository (e.g., your-org/flutter_wallet_card)
# 3. Set tag pattern: v{{version}} to match v[0-9]+.[0-9]+.[0-9]+*
# 4. No secrets required - uses temporary OIDC tokens
#
# This replaces the old manual credential approach with secure, temporary tokens

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'  # Matches v1.0.0, v1.0.0-beta, etc.
  workflow_dispatch:  # Allows manual triggering
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  # Pre-publish validation
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Dry run publish
        run: dart pub publish --dry-run

  # Modern OIDC-based publishing using dart-lang reusable workflow
  publish:
    needs: test
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    # with:
    #   working-directory: path/to/package/within/repository

  create-release:
    needs: [test, publish]
    runs-on: ubuntu-latest
    name: Create GitHub Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Get version from tag
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Extract changelog
        id: changelog
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          
          # Extract changelog for this version
          if [ -f "CHANGELOG.md" ]; then
            # Find the section for this version
            CHANGELOG_CONTENT=$(awk "/^## \[$VERSION\]/ {flag=1; next} /^## \[/ {flag=0} flag" CHANGELOG.md)
            
            if [ -z "$CHANGELOG_CONTENT" ]; then
              # Fallback: get content between first two ## headers
              CHANGELOG_CONTENT=$(awk '/^## / {if(++count==2) exit} count==1 && !/^## / {print}' CHANGELOG.md)
            fi
            
            # If still empty, use a default message
            if [ -z "$CHANGELOG_CONTENT" ]; then
              CHANGELOG_CONTENT="Release version $VERSION"
            fi
          else
            CHANGELOG_CONTENT="Release version $VERSION"
          fi
          
          # Save to file to preserve formatting
          echo "$CHANGELOG_CONTENT" > changelog_excerpt.md
          echo "changelog_file=changelog_excerpt.md" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body_path: ${{ steps.changelog.outputs.changelog_file }}
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.version, '-') }}

  update-docs:
    needs: [test, publish]
    runs-on: ubuntu-latest
    name: Update Documentation
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate documentation
        run: |
          # Generate API documentation
          dart doc --output docs/api
          
          # Update version in documentation files
          VERSION=${GITHUB_REF#refs/tags/v}
          find docs -name "*.md" -type f -exec sed -i "s/flutter_wallet_card: .*/flutter_wallet_card: ^$VERSION/g" {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
          commit_message: 'docs: update documentation for version ${{ steps.get_version.outputs.version }}'