name: Publish to pub.dev

# Automated publishing workflow using dart-lang/setup-dart reusable workflow
# Following official guidelines: https://dart.dev/tools/pub/automated-publishing
#
# Setup Requirements:
# 1. Enable automated publishing on pub.dev in package Admin tab
# 2. Configure GitHub repository (e.g., your-org/flutter_wallet_card)
# 3. Set tag pattern: v{{version}} to match v[0-9]+.[0-9]+.[0-9]+*
# 4. No secrets required - uses temporary OIDC tokens

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'  # Must match tag pattern on pub.dev: v{{version}}

# Publish using the reusable workflow from dart-lang
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    # with:
    #   working-directory: path/to/package/within/repository